
// Objective-C API for talking to the following Go packages
//
//	github.com/dreacot/dreacotdeliverylibagent
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Dreacotdeliverylibagent_FRAMEWORK_H__
#define __Dreacotdeliverylibagent_FRAMEWORK_H__

#include "Dreacotdeliverylibagent.objc.h"
#include "Universe.objc.h"

#endif
